// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCGcTMjlBY3zBqjy_CGDzAMXeYnFT9Xoo',
    appId: '1:458693507291:web:db04e29a7bbaeeec4bf4fe',
    messagingSenderId: '458693507291',
    projectId: 'waddi-platform-dev',
    authDomain: 'waddi-platform-dev.firebaseapp.com',
    storageBucket: 'waddi-platform-dev.firebasestorage.app',
    measurementId: 'G-LDEXL1MDV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE2ZQLUOtrDRwp0l-BGBsa-4FoHTY35cw',
    appId: '1:458693507291:android:fb2f4d3d55be2f904bf4fe',
    messagingSenderId: '458693507291',
    projectId: 'waddi-platform-dev',
    storageBucket: 'waddi-platform-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ol2QslIx-fEp9SvWtOqS5Qh_2Tq-qi8',
    appId: '1:458693507291:ios:7ddb77fb2ab749d14bf4fe',
    messagingSenderId: '458693507291',
    projectId: 'waddi-platform-dev',
    storageBucket: 'waddi-platform-dev.firebasestorage.app',
    androidClientId: '458693507291-4jrbaf9vdu9t0vcb37080ralk40fhirb.apps.googleusercontent.com',
    iosClientId: '458693507291-cnt3r1e1sfvae3p9obm0ugsfk4ql2gkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.waddi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3ol2QslIx-fEp9SvWtOqS5Qh_2Tq-qi8',
    appId: '1:458693507291:ios:4e629c07ca093c2a4bf4fe',
    messagingSenderId: '458693507291',
    projectId: 'waddi-platform-dev',
    storageBucket: 'waddi-platform-dev.firebasestorage.app',
    androidClientId: '458693507291-p4g13mv5tcoa748p8bh9c9o9ei0o9h08.apps.googleusercontent.com',
    iosClientId: '458693507291-gnri55a58a79bn600m5je6rgf9ff4m83.apps.googleusercontent.com',
    iosBundleId: 'com.example.waddiPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCGcTMjlBY3zBqjy_CGDzAMXeYnFT9Xoo',
    appId: '1:458693507291:web:75118fa6caf90be64bf4fe',
    messagingSenderId: '458693507291',
    projectId: 'waddi-platform-dev',
    authDomain: 'waddi-platform-dev.firebaseapp.com',
    storageBucket: 'waddi-platform-dev.firebasestorage.app',
    measurementId: 'G-1HQ27WML61',
  );

}